# This rule is not used by the project kafkaagentswarm itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to swarm.kafkaagentswarm.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kafkaagentswarm
    app.kubernetes.io/managed-by: kustomize
  name: agentswarm-viewer-role
rules:
- apiGroups:
  - swarm.kafkaagentswarm.io
  resources:
  - agentswarms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - swarm.kafkaagentswarm.io
  resources:
  - agentswarms/status
  verbs:
  - get
